# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site settings
title: BFFA
# email: Martaadmin@hardella.com
description:  # this means to ignore newlines until "baseurl:"

author:


comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            : "hardella"

analytics:
  provider: custom

# Build settings
future: true
markdown: kramdown
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
gems:
  - jekyll-feed
  - jekyll-polyglot
exclude:
  - Gemfile
  - Gemfile.lock
locale: "ru"
languages: ["ru", "en"]
default_lang: "ru"
lang_vars: ["locale"]
parallel_localization: true

collections:
  docs:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

include: ["_pages"]

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: true
      sidebar:
        nav: "docs"
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: false
      author_profile: false
      share: true
      comments: true
